### PR TITLE
gamagu/feature/193 [FAIL] Implement datamanagement 

### PR DESCRIPTION
**Pull request by Gamagu**

### CODE REVIEW

**Review by JJthere — CHANGES_REQUESTED** [review]
Naming conventions...

**Comment by Gamagu** [comment]
> Naming conventions...

Okey please mark every variable which is wrong :)

**Review by SirSimon04 — APPROVED** [review]
LGTM

**Review by SirSimon04 — APPROVED** [review]

**Review by JJthere — APPROVED** [review]
LGTM

**Pull request merged**
